HEADERS += autre/utilitaire.h \
    base_donnees/attaques/effets/effettauxpvrestants.h \
    base_donnees/attaques/effets/effettauxpvpvmax.h \
    base_donnees/attaques/effets/effettauxdegats.h \
    base_donnees/attaques/effets/effettaux.h \
    base_donnees/attaques/effets/effetstatut.h \
    base_donnees/attaques/effets/effetstatistique.h \
    base_donnees/attaques/effets/effetmultpuissattaque.h \
    base_donnees/attaques/effets/effetdegats.h \
    base_donnees/attaques/effets/effetclimat.h \
    base_donnees/attaques/effets/effetantiimmu.h \
    base_donnees/attaques/effets/effet.h \
    base_donnees/attaques/ficheattaque.h \
    base_donnees/capacites/fichecapacite.h \
    base_donnees/cartes/tuile.h \
    base_donnees/cartes/plateauligue.h \
    base_donnees/cartes/plateau.h \
    base_donnees/cartes/ligue.h \
    base_donnees/cartes/lieu.h \
    base_donnees/cartes/environnementligue.h \
    base_donnees/cartes/environnement.h \
    base_donnees/evolution/evolutionplace.h \
    base_donnees/evolution/evolutionpierreevolutivegenre.h \
    base_donnees/evolution/evolutionpierreevolutive.h \
    base_donnees/evolution/evolutionobjet.h \
    base_donnees/evolution/evolutionniveaugenre.h \
    base_donnees/evolution/evolutionniveau.h \
    base_donnees/evolution/evolutionconditionstat.h \
    base_donnees/evolution/evolutionbonheur.h \
    base_donnees/evolution/evolutionattaque.h \
    base_donnees/evolution/evolution.h \
    base_donnees/objets/soinstatut.h \
    base_donnees/objets/soinpvstatut.h \
    base_donnees/objets/soinpv.h \
    base_donnees/objets/soinpp.h \
    base_donnees/objets/soin.h \
    base_donnees/objets/revente.h \
    base_donnees/objets/repousse.h \
    base_donnees/objets/plaque.h \
    base_donnees/objets/pierreevo.h \
    base_donnees/objets/objetevo.h \
    base_donnees/objets/objetattachablecombat.h \
    base_donnees/objets/objet.h \
    base_donnees/objets/module.h \
    base_donnees/objets/fossile.h \
    base_donnees/objets/boost.h \
    base_donnees/objets/ball.h \
    base_donnees/objets/baie.h \
    base_donnees/personnages/personnage.h \
    base_donnees/personnages/dresseurligue.h \
    base_donnees/personnages/dresseur1.h \
    base_donnees/personnages/dresseur.h \
    base_donnees/personnages/champion.h \
    base_donnees/pokemon/pokemonsauvage.h \
    base_donnees/pokemon/pokemondresse.h \
    base_donnees/pokemon/pokemon.h \
    base_donnees/pokemon/fichepokemon.h \
    base_donnees/initdonnees.h \
    base_donnees/donnees.h \
    combat/transfertrelais.h \
    flux/flux.h \
    math/montecarlo/montecarlonombre.h \
    math/montecarlo/montecarlo.h \
    serialisable/base_donnees/hashmap.h \
    serialisable/combat/elementscombat.h \
    serialisable/combat/creaturecombat.h \
    serialisable/combat/combattant.h \
    serialisable/coordonnees/coordonnees.h \
    serialisable/difficulte/difficulte.h \
    serialisable/math/taux.h \
    serialisable/math/entierpositif.h \
    serialisable/math/entier.h \
    serialisable/partie/partie.h \
    serialisable/pokemon/pokemonutilisateur.h \
    serialisable/pokemon/oeufpokemon.h \
    serialisable/utilisateur/utilisateur.h \
    serialisable/utilisateur/inventaire.h \
    ihm/fenetre.h \
    ihm/boutons/bouton.h \
    ihm/hors_combat/scenehorscombat.h \
    ihm/combat/etiquettes/etiquettecreatcombat.h \
    ihm/combat/scenecombat.h \
    ihm/combat/etiquettes/imagecreaturecombat.h \
    ihm/combat/etiquettes/barre.h \
    ihm/combat/fiches/fichecreature.h \
    ihm/combat/etiquettes/etiquettecombattant.h \
    ihm/combat/etiquettes/etiquetteattaque.h \
    ihm/combat/fiches/ficheelements.h \
    ihm/combat/etiquettes/etiquetteequipe.h \
    ihm/combat/etiquettes/etiquetteposition.h \
    ihm/combat/fiches/ficheactions.h \
    ihm/boutons/touche.h \
    ihm/boutons/clavier.h \
    ihm/boutons/choixheros.h \
    ihm/hors_combat/etiquettes/etiquettepkut.h \
    ihm/hors_combat/etiquettes/etiquetteoeuf.h \
    ihm/hors_combat/fiches/fichepkutequipe.h \
    ihm/hors_combat/fiches/ficheoeuf.h \
    ihm/hors_combat/gestionequipe.h \
    ihm/boutons/claviernumerique.h \
    ihm/hors_combat/interactions.h \
    ihm/hors_combat/fiches/fichepkutboite.h \
    ihm/hors_combat/gestionboite.h \
    ihm/hors_combat/etiquettes/miniature.h \
    ihm/hors_combat/gestioninventaire.h \
    ihm/boutons/boutontype.h \
    ihm/boutons/boutonobjet.h \
    ihm/hors_combat/gestionachatvente.h \
    ihm/boutons/boutonachatvente.h \
    ihm/hors_combat/gestionfossile.h \
    ihm/hors_combat/fiches/fichepartie.h \
    ihm/curseurs/curseur.h \
    ihm/hors_combat/gestionoption.h \
    ihm/boutons/boutonchoix.h \
    ihm/hors_combat/gestionvol.h \
    serialisable/parametrelogiciel.h
SOURCES += autre/utilitaire.cpp \
    base_donnees/attaques/effets/effettauxpvrestants.cpp \
    base_donnees/attaques/effets/effettauxpvpvmax.cpp \
    base_donnees/attaques/effets/effettauxdegats.cpp \
    base_donnees/attaques/effets/effettaux.cpp \
    base_donnees/attaques/effets/effetstatut.cpp \
    base_donnees/attaques/effets/effetstatistique.cpp \
    base_donnees/attaques/effets/effetmultpuissattaque.cpp \
    base_donnees/attaques/effets/effetdegats.cpp \
    base_donnees/attaques/effets/effetclimat.cpp \
    base_donnees/attaques/effets/effetantiimmu.cpp \
    base_donnees/attaques/effets/effet.cpp \
    base_donnees/attaques/ficheattaque.cpp \
    base_donnees/capacites/fichecapacite.cpp \
    base_donnees/cartes/tuile.cpp \
    base_donnees/cartes/plateauligue.cpp \
    base_donnees/cartes/plateau.cpp \
    base_donnees/cartes/ligue.cpp \
    base_donnees/cartes/lieu.cpp \
    base_donnees/cartes/environnementligue.cpp \
    base_donnees/cartes/environnement.cpp \
    base_donnees/evolution/evolutionplace.cpp \
    base_donnees/evolution/evolutionpierreevolutivegenre.cpp \
    base_donnees/evolution/evolutionpierreevolutive.cpp \
    base_donnees/evolution/evolutionobjet.cpp \
    base_donnees/evolution/evolutionniveaugenre.cpp \
    base_donnees/evolution/evolutionniveau.cpp \
    base_donnees/evolution/evolutionconditionstat.cpp \
    base_donnees/evolution/evolutionbonheur.cpp \
    base_donnees/evolution/evolutionattaque.cpp \
    base_donnees/evolution/evolution.cpp \
    base_donnees/objets/soinstatut.cpp \
    base_donnees/objets/soinpvstatut.cpp \
    base_donnees/objets/soinpv.cpp \
    base_donnees/objets/soinpp.cpp \
    base_donnees/objets/soin.cpp \
    base_donnees/objets/revente.cpp \
    base_donnees/objets/repousse.cpp \
    base_donnees/objets/plaque.cpp \
    base_donnees/objets/pierreevo.cpp \
    base_donnees/objets/objetevo.cpp \
    base_donnees/objets/objetattachablecombat.cpp \
    base_donnees/objets/objet.cpp \
    base_donnees/objets/module.cpp \
    base_donnees/objets/fossile.cpp \
    base_donnees/objets/boost.cpp \
    base_donnees/objets/ball.cpp \
    base_donnees/objets/baie.cpp \
    base_donnees/personnages/personnage.cpp \
    base_donnees/personnages/dresseurligue.cpp \
    base_donnees/personnages/dresseur1.cpp \
    base_donnees/personnages/dresseur.cpp \
    base_donnees/personnages/champion.cpp \
    base_donnees/pokemon/pokemonsauvage.cpp \
    base_donnees/pokemon/pokemondresse.cpp \
    base_donnees/pokemon/pokemon.cpp \
    base_donnees/pokemon/fichepokemon.cpp \
    base_donnees/initdonnees.cpp \
    base_donnees/donnees.cpp \
    flux/flux.cpp \
    math/montecarlo/montecarlonombre.cpp \
    serialisable/combat/elementscombat.cpp \
    serialisable/combat/creaturecombat.cpp \
    serialisable/combat/combattant.cpp \
    serialisable/coordonnees/coordonnees.cpp \
    serialisable/difficulte/difficulte.cpp \
    serialisable/math/taux.cpp \
    serialisable/math/entierpositif.cpp \
    serialisable/math/entier.cpp \
    serialisable/partie/partie.cpp \
    serialisable/pokemon/pokemonutilisateur.cpp \
    serialisable/pokemon/oeufpokemon.cpp \
    serialisable/utilisateur/utilisateur.cpp \
    serialisable/utilisateur/inventaire.cpp \
    main.cpp \
    ihm/fenetre.cpp \
    ihm/boutons/bouton.cpp \
    ihm/hors_combat/scenehorscombat.cpp \
    ihm/combat/etiquettes/etiquettecreatcombat.cpp \
    ihm/combat/scenecombat.cpp \
    ihm/combat/etiquettes/imagecreaturecombat.cpp \
    ihm/combat/etiquettes/barre.cpp \
    ihm/combat/fiches/fichecreature.cpp \
    ihm/combat/etiquettes/etiquettecombattant.cpp \
    ihm/combat/etiquettes/etiquetteattaque.cpp \
    ihm/combat/fiches/ficheelements.cpp \
    ihm/combat/etiquettes/etiquetteequipe.cpp \
    ihm/combat/etiquettes/etiquetteposition.cpp \
    ihm/combat/fiches/ficheactions.cpp \
    ihm/boutons/touche.cpp \
    ihm/boutons/clavier.cpp \
    ihm/boutons/choixheros.cpp \
    ihm/hors_combat/etiquettes/etiquettepkut.cpp \
    ihm/hors_combat/etiquettes/etiquetteoeuf.cpp \
    ihm/hors_combat/fiches/fichepkutequipe.cpp \
    ihm/hors_combat/fiches/ficheoeuf.cpp \
    ihm/hors_combat/gestionequipe.cpp \
    ihm/boutons/claviernumerique.cpp \
    ihm/hors_combat/interactions.cpp \
    ihm/hors_combat/fiches/fichepkutboite.cpp \
    ihm/hors_combat/gestionboite.cpp \
    ihm/hors_combat/etiquettes/miniature.cpp \
    ihm/hors_combat/gestioninventaire.cpp \
    ihm/boutons/boutontype.cpp \
    ihm/boutons/boutonobjet.cpp \
    ihm/hors_combat/gestionachatvente.cpp \
    ihm/boutons/boutonachatvente.cpp \
    ihm/hors_combat/gestionfossile.cpp \
    ihm/hors_combat/fiches/fichepartie.cpp \
    ihm/curseurs/curseur.cpp \
    ihm/hors_combat/gestionoption.cpp \
    ihm/boutons/boutonchoix.cpp \
    ihm/hors_combat/gestionvol.cpp \
    serialisable/parametrelogiciel.cpp
CONFIG += debug \
    console
