#include "base_donnees/initdonnees.h"
#include "base_donnees/donnees.h"

InitDonnees::InitDonnees():QThread(0){
	donnees=NULL;
}

Donnees *InitDonnees::res()const{
	return donnees;
}

void InitDonnees::run(){
	int avancement_=0;
	donnees=new Donnees();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_equivalents_genre();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_heros();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_dossiers_tuiles();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_dossiers_dresseurs_macro();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_dossiers_dresseurs_micro();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_liens();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_elements_map();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_images_env_def();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_types();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_tuiles_importees();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_dresseurs_macros();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_dresseurs_micros();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_obstacles(Donnees::ARBRE);
	avancement_++;
	emit avancement(avancement_);
	donnees->init_obstacles(Donnees::ROCHER_DEST);
	avancement_++;
	emit avancement(avancement_);
	donnees->init_obstacles(Donnees::ROCHER_AMOV);
	avancement_++;
	emit avancement(avancement_);
	donnees->init_obstacles(Donnees::TOURBILLON);
	avancement_++;
	emit avancement(avancement_);
	donnees->init_descriptions_complements();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques_touchant_pseudo_invuln();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques_lilliput();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_puissance_degommage();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_noms_objets();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_type_lieux();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_ct();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_cs();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_pokedex();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_bases_evos();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_miniatures();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_images_dos_f();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_images_dos_m();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_images_face_f();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_images_face_m();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_rapport_masse_max();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_masse_moy();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_capacites();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_prix_pierres_objets_evo();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_objets();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_images_objets();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_table_types_base();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_types_ball_meteo();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_lois_fin_tour();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_abri_attaques();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_assistance_attaques();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques_1_pp_plus_tours();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques_actives_definies();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques_actives_indefinies();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques_anti_soin();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques_cc();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_auto_degel();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_blabla_dodo_attaques();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_camouflage();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_effets_ec_degommage();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_clonage_bloc();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_clonage_non_bloc();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_copie_attaques();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_encore_attaques();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_gravite();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_metronome();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_mimique_attaques();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_mimique_attaques2();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_non_affecte_abri();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_non_affecte_poudre_claire();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_relations_combattants();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_saisie_attaques();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_switch_force();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_force_nature();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_types_immu();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_reflet_magik();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_attaques_piegeantes();
	avancement_++;
	emit avancement(avancement_);
	donnees->init_donnees_carto();
	avancement_++;
	emit avancement(avancement_);
}


